package = "rustaceanvim"
lua = "==5.1"

[source]
url = "https://github.com/mrcjkb/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
dev = "git+https://github.com/mrcjkb/$(PACKAGE).git"

[description]
summary = "ðŸ¦€ Supercharge your Rust experience in Neovim! A heavily modified fork of rust-tools.nvim"
maintainer = "mrcjkb"
labels = [ "dap", "debug-adapter-protocol", "language-server-protocol", "lsp", "neovim", "nvim", "plugin", "rust", "rust-analyzer", "rust-lang", "rust-tools" ]
license = "GPL-2.0-only"

[build]
type = "builtin"
copy_directories = [
  "doc",
  "ftplugin"
]

[test]
type = "busted-nlua"

[test_dependencies]
nvim-dap = "0.10.0-1"
neotest = "5.13.1-1"
