package = "rustaceanvim"
version = "0.1.0"
lua = "==5.1"

[source]
url = "https://github.com/mrcjkb/$(PACKAGE)/archive/refs/tags/v$(VERSION).zip"
dev = "git+https://github.com/mrcjkb/$(PACKAGE).git"

[description]
summary = "ðŸ¦€ Supercharge your Rust experience in Neovim! A heavily modified fork of rust-tools.nvim"
maintainer = "mrcjkb"
labels = [ "dap", "debug-adapter-protocol", "language-server-protocol", "lsp", "neovim", "nvim", "plugin", "rust", "rust-analyzer", "rust-lang", "rust-tools" ]
license = "GPL-2.0-only"

[test-dependencies]
"nlua" = "~> 0.3"
"busted" = "~> 2"

[build]
type = "builtin"
