---
name: "[Debug] fetch tags"
on:
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Print tags
        run: git --no-pager --tag
