---
name: "Push to LuaRocks"
on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  luarocks-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Lux
        uses: lumen-oss/gh-actions-lux@v1
        with:
          version: 0.18.11

      - name: Upload
        run: |
          lx --nvim upload
        env:
          LUX_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
